import { IDASFactory } from "./api/IDAS";
import { RESTClient } from "./api/RESTClient";
import { initIDAS } from "./api/authUtils";
export { IDASFactory, initIDAS, RESTClient };

export { createApi, fluentApi } from "./api/fluentApi";
export { createIDASApi, idasFluentApi } from "./api/idasFluentApi";
export { createAuthManager, fluentIdasAuthManager } from "./api/fluentAuthManager";
export { fetchEnvConfig } from "./api/fluentEnvUtils";
export { restClient } from "./api/fluentRestClient";

// Business Routines APIs
export * from "./api/business/index.js";

// DTO Type Definitions - re-exported for JSDoc type imports
// Usage: @typedef {import('@gandalan/idas-weblibs').VorgangDTO} VorgangDTO
export * from "./api/dtos/index.js";

// BEGIN GENERATED ROOT DTO TYPEDEFS
// DTO Type Definitions - copied to the package root for stable JSDoc imports
// This block is generated by scripts/generate-root-dto-typedefs.mjs from ./api/dtos/index.js
/** @typedef {import("./api/dtos/index.js").ApiVersionDTO} ApiVersionDTO */
/** @typedef {import("./api/dtos/index.js").ChangeDTO} ChangeDTO */
/** @typedef {import("./api/dtos/index.js").ChangeInfoDTO} ChangeInfoDTO */
/** @typedef {import("./api/dtos/index.js").ContractDTO} ContractDTO */
/** @typedef {import("./api/dtos/index.js").CreateServiceTokenRequestDTO} CreateServiceTokenRequestDTO */
/** @typedef {import("./api/dtos/index.js").DevOpsStatusDTO} DevOpsStatusDTO */
/** @typedef {import("./api/dtos/index.js").ExtendedStatusCodeDTO} ExtendedStatusCodeDTO */
/** @typedef {import("./api/dtos/index.js").TemplateDTO} TemplateDTO */
/** @typedef {import("./api/dtos/index.js").UpdateInfoDTO} UpdateInfoDTO */
/** @typedef {import("./api/dtos/index.js").WebJobHistorieDTO} WebJobHistorieDTO */
/** @typedef {import("./api/dtos/index.js").IndiFarbDatenDTO} IndiFarbDatenDTO */
/** @typedef {import("./api/dtos/index.js").KatalogArtikelIndiDatenDTO} KatalogArtikelIndiDatenDTO */
/** @typedef {import("./api/dtos/index.js").MaterialBearbeitungsMethodeDTO} MaterialBearbeitungsMethodeDTO */
/** @typedef {import("./api/dtos/index.js").AVReserviertItemDTO} AVReserviertItemDTO */
/** @typedef {import("./api/dtos/index.js").BearbeitungsKuerzelDTO} BearbeitungsKuerzelDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionAVDTO} BelegPositionAVDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionAVListItemDTO} BelegPositionAVListItemDTO */
/** @typedef {import("./api/dtos/index.js").PCodeStatistikDTO} PCodeStatistikDTO */
/** @typedef {import("./api/dtos/index.js").PositionSerieItemDTO} PositionSerieItemDTO */
/** @typedef {import("./api/dtos/index.js").ProfilKuerzelDTO} ProfilKuerzelDTO */
/** @typedef {import("./api/dtos/index.js").SerieAuslastungDTO} SerieAuslastungDTO */
/** @typedef {import("./api/dtos/index.js").SerieDruckInfoDTO} SerieDruckInfoDTO */
/** @typedef {import("./api/dtos/index.js").SerieDTO} SerieDTO */
/** @typedef {import("./api/dtos/index.js").SerieHistorieDTO} SerieHistorieDTO */
/** @typedef {import("./api/dtos/index.js").SerienMaterialEditDTO} SerienMaterialEditDTO */
/** @typedef {import("./api/dtos/index.js").VirtualSerieWithAuslastungDTO} VirtualSerieWithAuslastungDTO */
/** @typedef {import("./api/dtos/index.js").AdresseDruckDTO} AdresseDruckDTO */
/** @typedef {import("./api/dtos/index.js").BaseListItemDTO} BaseListItemDTO */
/** @typedef {import("./api/dtos/index.js").BelegArt} BelegArt */
/** @typedef {import("./api/dtos/index.js").BelegartWechselDTO} BelegartWechselDTO */
/** @typedef {import("./api/dtos/index.js").BelegDruckDTO} BelegDruckDTO */
/** @typedef {import("./api/dtos/index.js").BelegDTO} BelegDTO */
/** @typedef {import("./api/dtos/index.js").BelegHistorieDTO} BelegHistorieDTO */
/** @typedef {import("./api/dtos/index.js").BelegHistorienDTO} BelegHistorienDTO */
/** @typedef {import("./api/dtos/index.js").BelegNummerSettingDTO} BelegNummerSettingDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionDatenDTO} BelegPositionDatenDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionDruckDTO} BelegPositionDruckDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionDTO} BelegPositionDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionHistorieDTO} BelegPositionHistorieDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionHistorienDTO} BelegPositionHistorienDTO */
/** @typedef {import("./api/dtos/index.js").BelegPositionSonderwunschDTO} BelegPositionSonderwunschDTO */
/** @typedef {import("./api/dtos/index.js").BelegSaldoDruckDTO} BelegSaldoDruckDTO */
/** @typedef {import("./api/dtos/index.js").BelegSaldoDTO} BelegSaldoDTO */
/** @typedef {import("./api/dtos/index.js").BelegSerienInfoDTO} BelegSerienInfoDTO */
/** @typedef {import("./api/dtos/index.js").BelegStatus} BelegStatus */
/** @typedef {import("./api/dtos/index.js").BelegStatusDTO} BelegStatusDTO */
/** @typedef {import("./api/dtos/index.js").BelegWorkflow} BelegWorkflow */
/** @typedef {import("./api/dtos/index.js").BestellungListItemDTO} BestellungListItemDTO */
/** @typedef {import("./api/dtos/index.js").CalculationInfoDTO} CalculationInfoDTO */
/** @typedef {import("./api/dtos/index.js").KapaFarbArt} KapaFarbArt */
/** @typedef {import("./api/dtos/index.js").Kapazitaetsvorgabe} Kapazitaetsvorgabe */
/** @typedef {import("./api/dtos/index.js").KapazitaetsvorgabenDTO} KapazitaetsvorgabenDTO */
/** @typedef {import("./api/dtos/index.js").MaterialBestellungListItemDTO} MaterialBestellungListItemDTO */
/** @typedef {import("./api/dtos/index.js").RechnungsNummer} RechnungsNummer */
/** @typedef {import("./api/dtos/index.js").SerieInfoDTO} SerieInfoDTO */
/** @typedef {import("./api/dtos/index.js").VorgangDTO} VorgangDTO */
/** @typedef {import("./api/dtos/index.js").VorgangExtendedDTO} VorgangExtendedDTO */
/** @typedef {import("./api/dtos/index.js").VorgangHistorieDTO} VorgangHistorieDTO */
/** @typedef {import("./api/dtos/index.js").VorgangHistorienDTO} VorgangHistorienDTO */
/** @typedef {import("./api/dtos/index.js").VorgangListItemDTO} VorgangListItemDTO */
/** @typedef {import("./api/dtos/index.js").VorgangNachrichtAnhangDTO} VorgangNachrichtAnhangDTO */
/** @typedef {import("./api/dtos/index.js").VorgangNachrichtDTO} VorgangNachrichtDTO */
/** @typedef {import("./api/dtos/index.js").VorgangStatusDTO} VorgangStatusDTO */
/** @typedef {import("./api/dtos/index.js").VorgangStatusTableDTO} VorgangStatusTableDTO */
/** @typedef {import("./api/dtos/index.js").VorgangTextStatusDTO} VorgangTextStatusDTO */
/** @typedef {import("./api/dtos/index.js").ZusatztextDTO} ZusatztextDTO */
/** @typedef {import("./api/dtos/index.js").BenutzerDTO} BenutzerDTO */
/** @typedef {import("./api/dtos/index.js").BerechtigungDTO} BerechtigungDTO */
/** @typedef {import("./api/dtos/index.js").LoginAttemptDTO} LoginAttemptDTO */
/** @typedef {import("./api/dtos/index.js").LoginAttemptResultDTO} LoginAttemptResultDTO */
/** @typedef {import("./api/dtos/index.js").LoginDTO} LoginDTO */
/** @typedef {import("./api/dtos/index.js").PasswortAendernDTO} PasswortAendernDTO */
/** @typedef {import("./api/dtos/index.js").RefreshTokenDTO} RefreshTokenDTO */
/** @typedef {import("./api/dtos/index.js").RolleDTO} RolleDTO */
/** @typedef {import("./api/dtos/index.js").UserAuthTokenDTO} UserAuthTokenDTO */
/** @typedef {import("./api/dtos/index.js").ZustimmungsInfoDTO} ZustimmungsInfoDTO */
/** @typedef {import("./api/dtos/index.js").ILayoutBelegDruck} ILayoutBelegDruck */
/** @typedef {import("./api/dtos/index.js").LayoutBelegDruckDTO} LayoutBelegDruckDTO */
/** @typedef {import("./api/dtos/index.js").AddRechnungSammelrechnungDTO} AddRechnungSammelrechnungDTO */
/** @typedef {import("./api/dtos/index.js").BelegeInfoDTO} BelegeInfoDTO */
/** @typedef {import("./api/dtos/index.js").CreateSammelrechnungDTO} CreateSammelrechnungDTO */
/** @typedef {import("./api/dtos/index.js").Lieferungstyp} Lieferungstyp */
/** @typedef {import("./api/dtos/index.js").SammelrechnungDTO} SammelrechnungDTO */
/** @typedef {import("./api/dtos/index.js").SammelrechnungListItemDTO} SammelrechnungListItemDTO */
/** @typedef {import("./api/dtos/index.js").SammelrechnungPositionenDTO} SammelrechnungPositionenDTO */
/** @typedef {import("./api/dtos/index.js").SammelrechnungSaldenDTO} SammelrechnungSaldenDTO */
/** @typedef {import("./api/dtos/index.js").SetFakturaDTO} SetFakturaDTO */
/** @typedef {import("./api/dtos/index.js").FarbeDTO} FarbeDTO */
/** @typedef {import("./api/dtos/index.js").FarbGruppeDTO} FarbGruppeDTO */
/** @typedef {import("./api/dtos/index.js").FarbgruppenaufpreiseDTO} FarbgruppenaufpreiseDTO */
/** @typedef {import("./api/dtos/index.js").FarbgruppeSettingsDTO} FarbgruppeSettingsDTO */
/** @typedef {import("./api/dtos/index.js").FarbKuerzelDTO} FarbKuerzelDTO */
/** @typedef {import("./api/dtos/index.js").FarbKuerzelGruppeDTO} FarbKuerzelGruppeDTO */
/** @typedef {import("./api/dtos/index.js").ProduzentenFarbGruppeDTO} ProduzentenFarbGruppeDTO */
/** @typedef {import("./api/dtos/index.js").AdresseDTO} AdresseDTO */
/** @typedef {import("./api/dtos/index.js").AppActivationStatusDTO} AppActivationStatusDTO */
/** @typedef {import("./api/dtos/index.js").BeleganschriftDTO} BeleganschriftDTO */
/** @typedef {import("./api/dtos/index.js").KontaktDTO} KontaktDTO */
/** @typedef {import("./api/dtos/index.js").KontaktListItemDTO} KontaktListItemDTO */
/** @typedef {import("./api/dtos/index.js").PersonDTO} PersonDTO */
/** @typedef {import("./api/dtos/index.js").ZusatzanschriftDTO} ZusatzanschriftDTO */
/** @typedef {import("./api/dtos/index.js").LagerbestandDTO} LagerbestandDTO */
/** @typedef {import("./api/dtos/index.js").LagerbuchungDTO} LagerbuchungDTO */
/** @typedef {import("./api/dtos/index.js").LagerReservierungDTO} LagerReservierungDTO */
/** @typedef {import("./api/dtos/index.js").JobStatusEntryDTO} JobStatusEntryDTO */
/** @typedef {import("./api/dtos/index.js").JobStatusResponseDTO} JobStatusResponseDTO */
/** @typedef {import("./api/dtos/index.js").MailJobInfo} MailJobInfo */
/** @typedef {import("./api/dtos/index.js").FreigabeArt} FreigabeArt */
/** @typedef {import("./api/dtos/index.js").FreigabeLevel} FreigabeLevel */
/** @typedef {import("./api/dtos/index.js").MandantDTO} MandantDTO */
/** @typedef {import("./api/dtos/index.js").MandantFreigabeDTO} MandantFreigabeDTO */
/** @typedef {import("./api/dtos/index.js").ProduzentAktivierenDTO} ProduzentAktivierenDTO */
/** @typedef {import("./api/dtos/index.js").NachrichtenDTO} NachrichtenDTO */
/** @typedef {import("./api/dtos/index.js").ProduktGruppeDTO} ProduktGruppeDTO */
/** @typedef {import("./api/dtos/index.js").AblageDTO} AblageDTO */
/** @typedef {import("./api/dtos/index.js").AblageFachDTO} AblageFachDTO */
/** @typedef {import("./api/dtos/index.js").BearbeitungDTO} BearbeitungDTO */
/** @typedef {import("./api/dtos/index.js").BerechnungParameterDTO} BerechnungParameterDTO */
/** @typedef {import("./api/dtos/index.js").BerechnungResultDTO} BerechnungResultDTO */
/** @typedef {import("./api/dtos/index.js").EtikettDatenDTO} EtikettDatenDTO */
/** @typedef {import("./api/dtos/index.js").EtikettDTO} EtikettDTO */
/** @typedef {import("./api/dtos/index.js").FachzuordnungResultDTO} FachzuordnungResultDTO */
/** @typedef {import("./api/dtos/index.js").GesamtLieferzusageBuchungDTO} GesamtLieferzusageBuchungDTO */
/** @typedef {import("./api/dtos/index.js").GesamtLieferzusageDTO} GesamtLieferzusageDTO */
/** @typedef {import("./api/dtos/index.js").GesamtMaterialbedarfDTO} GesamtMaterialbedarfDTO */
/** @typedef {import("./api/dtos/index.js").GesamtMaterialbedarfGetReturn} GesamtMaterialbedarfGetReturn */
/** @typedef {import("./api/dtos/index.js").ILagerLogikDTO} ILagerLogikDTO */
/** @typedef {import("./api/dtos/index.js").KatalogArtikelArt} KatalogArtikelArt */
/** @typedef {import("./api/dtos/index.js").LieferzusageDTO} LieferzusageDTO */
/** @typedef {import("./api/dtos/index.js").MaterialbedarfCutOptimization} MaterialbedarfCutOptimization */
/** @typedef {import("./api/dtos/index.js").MaterialbedarfDTO} MaterialbedarfDTO */
/** @typedef {import("./api/dtos/index.js").MaterialbedarfStatiDTO} MaterialbedarfStatiDTO */
/** @typedef {import("./api/dtos/index.js").PositionsDatenDTO} PositionsDatenDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsDatenDTO} ProduktionsDatenDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsfreigabeItemDTO} ProduktionsfreigabeItemDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsInfoBelegDTO} ProduktionsInfoBelegDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsInfoBelegPositionAVDTO} ProduktionsInfoBelegPositionAVDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsInfoBelegPositionDTO} ProduktionsInfoBelegPositionDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsInfoDTO} ProduktionsInfoDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsStatiWerteDTO} ProduktionsStatiWerteDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsStatusDTO} ProduktionsStatusDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsStatusHistorieDTO} ProduktionsStatusHistorieDTO */
/** @typedef {import("./api/dtos/index.js").SaegeDatenHistorieDTO} SaegeDatenHistorieDTO */
/** @typedef {import("./api/dtos/index.js").SaegeDatenResultDTO} SaegeDatenResultDTO */
/** @typedef {import("./api/dtos/index.js").SaegeKonfigurationDTO} SaegeKonfigurationDTO */
/** @typedef {import("./api/dtos/index.js").SaegemassKorrekturDTO} SaegemassKorrekturDTO */
/** @typedef {import("./api/dtos/index.js").SaegemassKorrekturSatzDTO} SaegemassKorrekturSatzDTO */
/** @typedef {import("./api/dtos/index.js").SchnittoptimierungsOptionen} SchnittoptimierungsOptionen */
/** @typedef {import("./api/dtos/index.js").SonderwuenscheDTO} SonderwuenscheDTO */
/** @typedef {import("./api/dtos/index.js").ZusammenfassungsOptionen} ZusammenfassungsOptionen */
/** @typedef {import("./api/dtos/index.js").ArtosStartSettingsDTO} ArtosStartSettingsDTO */
/** @typedef {import("./api/dtos/index.js").AufpreisAnpassungDTO} AufpreisAnpassungDTO */
/** @typedef {import("./api/dtos/index.js").CsvExportCombinationDTO} CsvExportCombinationDTO */
/** @typedef {import("./api/dtos/index.js").ExportArtikelArt} ExportArtikelArt */
/** @typedef {import("./api/dtos/index.js").ExportFarbArt} ExportFarbArt */
/** @typedef {import("./api/dtos/index.js").MaterialbedarfExportSettingsDTO} MaterialbedarfExportSettingsDTO */
/** @typedef {import("./api/dtos/index.js").MaterialbedarfExportType} MaterialbedarfExportType */
/** @typedef {import("./api/dtos/index.js").MaterialbedarfExportUserSettings} MaterialbedarfExportUserSettings */
/** @typedef {import("./api/dtos/index.js").MaterialBedarfLogik} MaterialBedarfLogik */
/** @typedef {import("./api/dtos/index.js").PreisermittlungsEinstellungenDTO} PreisermittlungsEinstellungenDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionProduktfamilieSettingsDTO} ProduktionProduktfamilieSettingsDTO */
/** @typedef {import("./api/dtos/index.js").ProduktionsSettingsDTO} ProduktionsSettingsDTO */
/** @typedef {import("./api/dtos/index.js").SLKServerSettingsDTO} SLKServerSettingsDTO */
/** @typedef {import("./api/dtos/index.js").BauteilDTO} BauteilDTO */
/** @typedef {import("./api/dtos/index.js").KomponenteDTO} KomponenteDTO */
/** @typedef {import("./api/dtos/index.js").KomponenteVariableDTO} KomponenteVariableDTO */
/** @typedef {import("./api/dtos/index.js").KomponenteVerknuepfungDTO} KomponenteVerknuepfungDTO */
/** @typedef {import("./api/dtos/index.js").KonturDTO} KonturDTO */
/** @typedef {import("./api/dtos/index.js").KonturElementDTO} KonturElementDTO */
/** @typedef {import("./api/dtos/index.js").OperationsPunktDTO} OperationsPunktDTO */
/** @typedef {import("./api/dtos/index.js").SchnittDTO} SchnittDTO */
/** @typedef {import("./api/dtos/index.js").SchnittKonturDTO} SchnittKonturDTO */
/** @typedef {import("./api/dtos/index.js").SchnittKonturOperationDTO} SchnittKonturOperationDTO */
/** @typedef {import("./api/dtos/index.js").FarbArt} FarbArt */
/** @typedef {import("./api/dtos/index.js").GuidListDTO} GuidListDTO */
/** @typedef {import("./api/dtos/index.js").InfoScreenConfigDTO} InfoScreenConfigDTO */
/** @typedef {import("./api/dtos/index.js").InfoScreenInitTypeDTO} InfoScreenInitTypeDTO */
/** @typedef {import("./api/dtos/index.js").InfoScreenModulSettingsDTO} InfoScreenModulSettingsDTO */
/** @typedef {import("./api/dtos/index.js").InfoScreenRowDTO} InfoScreenRowDTO */
/** @typedef {import("./api/dtos/index.js").KatalogArtikelDTO} KatalogArtikelDTO */
/** @typedef {import("./api/dtos/index.js").KatalogArtikelFarbZuordnungDTO} KatalogArtikelFarbZuordnungDTO */
/** @typedef {import("./api/dtos/index.js").KonfigSatzDTO} KonfigSatzDTO */
/** @typedef {import("./api/dtos/index.js").KonfigSatzEintragDTO} KonfigSatzEintragDTO */
/** @typedef {import("./api/dtos/index.js").KonfigSatzInfoDTO} KonfigSatzInfoDTO */
/** @typedef {import("./api/dtos/index.js").OberflaecheDTO} OberflaecheDTO */
/** @typedef {import("./api/dtos/index.js").ProduktFamilieDTO} ProduktFamilieDTO */
/** @typedef {import("./api/dtos/index.js").ProduktFamilieErsatzFarbZuordnungDTO} ProduktFamilieErsatzFarbZuordnungDTO */
/** @typedef {import("./api/dtos/index.js").ProduktFamilieFarbZuordnungDTO} ProduktFamilieFarbZuordnungDTO */
/** @typedef {import("./api/dtos/index.js").ProduktFamilienDTOListe} ProduktFamilienDTOListe */
/** @typedef {import("./api/dtos/index.js").PropertyValueCollection} PropertyValueCollection */
/** @typedef {import("./api/dtos/index.js").TagInfoDTO} TagInfoDTO */
/** @typedef {import("./api/dtos/index.js").TagVorlageDTO} TagVorlageDTO */
/** @typedef {import("./api/dtos/index.js").UIDefinitionDTO} UIDefinitionDTO */
/** @typedef {import("./api/dtos/index.js").UIEingabeFeldDTO} UIEingabeFeldDTO */
/** @typedef {import("./api/dtos/index.js").UIEingabeFeldInfoDTO} UIEingabeFeldInfoDTO */
/** @typedef {import("./api/dtos/index.js").UIEingabeFeldRegelNames} UIEingabeFeldRegelNames */
/** @typedef {import("./api/dtos/index.js").UIKonfiguratorFeldDTO} UIKonfiguratorFeldDTO */
/** @typedef {import("./api/dtos/index.js").UIScriptDTO} UIScriptDTO */
/** @typedef {import("./api/dtos/index.js").VarianteDTO} VarianteDTO */
/** @typedef {import("./api/dtos/index.js").VarianteDTOListe} VarianteDTOListe */
/** @typedef {import("./api/dtos/index.js").WarenGruppeDTO} WarenGruppeDTO */
/** @typedef {import("./api/dtos/index.js").WarenGruppeDTOListe} WarenGruppeDTOListe */
/** @typedef {import("./api/dtos/index.js").WerteListeDTO} WerteListeDTO */
/** @typedef {import("./api/dtos/index.js").WerteListeDTOListe} WerteListeDTOListe */
/** @typedef {import("./api/dtos/index.js").WerteListeItemDTO} WerteListeItemDTO */
/** @typedef {import("./api/dtos/index.js").MandantAndBelegPosGuidDTO} MandantAndBelegPosGuidDTO */
// END GENERATED ROOT DTO TYPEDEFS

// re-export all modules from the ui folder as named exports
export * from "./ui/index.js";

// BEGIN GENERATED ROOT BUSINESS TYPEDEFS
// Business API Type Definitions - copied to the package root for stable JSDoc imports
// This block is generated by scripts/generate-root-dto-typedefs.mjs from ./api/business/index.js
/** @typedef {import("./api/business/index.js").AblageApi} AblageApi */
/** @typedef {import("./api/business/index.js").AnpassungApi} AnpassungApi */
/** @typedef {import("./api/business/index.js").ArtikelApi} ArtikelApi */
/** @typedef {import("./api/business/index.js").AuthApi} AuthApi */
/** @typedef {import("./api/business/index.js").AvApi} AvApi */
/** @typedef {import("./api/business/index.js").BelegApi} BelegApi */
/** @typedef {import("./api/business/index.js").BelegPositionenApi} BelegPositionenApi */
/** @typedef {import("./api/business/index.js").BenutzerApi} BenutzerApi */
/** @typedef {import("./api/business/index.js").FakturaApi} FakturaApi */
/** @typedef {import("./api/business/index.js").FarbeApi} FarbeApi */
/** @typedef {import("./api/business/index.js").FileApi} FileApi */
/** @typedef {import("./api/business/index.js").HistorieApi} HistorieApi */
/** @typedef {import("./api/business/index.js").KontaktApi} KontaktApi */
/** @typedef {import("./api/business/index.js").LagerApi} LagerApi */
/** @typedef {import("./api/business/index.js").LieferungApi} LieferungApi */
/** @typedef {import("./api/business/index.js").MailApi} MailApi */
/** @typedef {import("./api/business/index.js").MandantApi} MandantApi */
/** @typedef {import("./api/business/index.js").MaterialApi} MaterialApi */
/** @typedef {import("./api/business/index.js").PrintApi} PrintApi */
/** @typedef {import("./api/business/index.js").ProduktionApi} ProduktionApi */
/** @typedef {import("./api/business/index.js").RechnungApi} RechnungApi */
/** @typedef {import("./api/business/index.js").SerienApi} SerienApi */
/** @typedef {import("./api/business/index.js").SettingsApi} SettingsApi */
/** @typedef {import("./api/business/index.js").SystemApi} SystemApi */
/** @typedef {import("./api/business/index.js").UiApi} UiApi */
/** @typedef {import("./api/business/index.js").UtilityApi} UtilityApi */
/** @typedef {import("./api/business/index.js").VorgangApi} VorgangApi */
// END GENERATED ROOT BUSINESS TYPEDEFS

/**
 * @typedef {import("./api/fluentApi").FluentApi} FluentApi
 * @typedef {import("./api/idasFluentApi").IDASFluentApi} IDASFluentApi
 * @typedef {import("./api/fluentAuthManager").FluentAuthManager} FluentAuthManager
 */

/**
 * @typedef {0 | 1 | 2} NeherApp3NotifyType
 */

/**
 * @typedef {Object} ArtikelstammEintrag
 * @property {string} [KatalogArtikelGuid]
 * @property {string} [KatalogNummer]
 * @property {string} [Katalognummer]
 * @property {string} [Nummer]
 */

/**
 * @typedef {Object} Variante
 * @property {string} [VarianteGuid]
 * @property {string} [Name]
 * @property {string} [Kuerzel]
 */

/**
 * @typedef {Object} Werteliste
 * @property {string} [WerteListeGuid]
 * @property {string} [Name]
 */

/**
 * @typedef {Object} NeherApp3ArtikelstammCache
 * @property {() => Promise<ArtikelstammEintrag[]>} getArtikelStamm
 * @property {() => Promise<Object[]>} getWarenGruppen
 * @property {(guid: string) => Promise<ArtikelstammEintrag | undefined>} getArtikelByGuid
 * @property {(nummer: string) => Promise<ArtikelstammEintrag | undefined>} getArtikelByKatalognummer
 */

/**
 * @typedef {Object} NeherApp3ErfassungCache
 * @property {() => Promise<Variante[]>} getVarianten
 * @property {(variantenNameOderKuerzel: string) => Promise<Variante | undefined>} getVariante
 * @property {() => Promise<Werteliste[]>} getWertelisten
 * @property {(name: string) => Promise<Werteliste | undefined>} getWerteliste
 * @property {() => Promise<Object[]>} getScripts
 * @property {(v: Variante) => void} createUIMachine
 */

/**
 * @typedef {Object} NeherApp3Props
 * @property {FluentApi} api
 * @property {FluentAuthManager} [authManager]
 * @property {IDASFluentApi} idas
 * @property {string} [mainCssPath]
 */

/** 
 * @typedef {Object} NeherApp3MenuItem
 * @property {string} [id] - Unique identifier for the menu item (auto-generated if not provided)
 * @property {boolean} [selected] - Indicates if the menu item is currently selected (managed by the menu system)
 * @property {string} [icon] - URL to an icon
 * @property {string|null} [url] - Relative URL to use for routes
 * @property {string} text - Display text
 * @property {string|null} [parent] - Parent menu item (optional). If not set, the item will be added to the top level menu.
 * @property {boolean} [hidden] - If true, the menu item will not be displayed
 */

/**
 * @typedef {NeherApp3Props & { neherapp3: NeherApp3 }} NeherApp3SetupContext
 */

/**
 * @typedef {Object} NeherApp3Module
 * @property {string} moduleName
 * @property {(context: NeherApp3SetupContext) => (void | Promise<void>)} [setup]
 * @property {(node: HTMLElement, props: NeherApp3SetupContext) => (void | function)} [mount] Must return an optional unmount function
 * @property {string} [embedUrl]
 * @property {string[]} [extraCSS]
 * @property {boolean} [useShadowDom] - If true, the app will be embedded in a shadow DOM. This is required for CSS isolation.
 */

/**
 * @typedef {Object} NeherApp3ApiCollection
 * @property {IDASFluentApi} [idas]
 * @property {FluentApi} [hostingEnvironment]
 */

/**
 * @typedef {Object} NeherApp3CacheCollection
 * @property {NeherApp3ArtikelstammCache} artikelstamm
 * @property {NeherApp3ErfassungCache} erfassung
 */

/**
 * @typedef {Object} NeherApp3
 * @property {(menuItem: NeherApp3MenuItem) => void} addMenuItem
 * @property {(appModule: NeherApp3Module | string) => Promise<void>} addApp
 * @property {(message: string, type?: NeherApp3NotifyType, cb?: function) => void} notify - Shows a notification. Type defaults to 0 (info). Callback is optional.
 * @property {NeherApp3ApiCollection} api
 * @property {NeherApp3CacheCollection} cache
 */

/**
 * Global NeherApp3 instance
 * @type {NeherApp3}
 * @global
 */
globalThis.neherapp3 = /** @type {NeherApp3} */ (globalThis.neherapp3 || {});

